version: '3'



services:

  postgres_auth_db:
    image: 'postgres:latest'
    ports:
      - 5429:5432
    environment:
      - 'POSTGRES_USER=aleshkey'
      - 'POSTGRES_PASSWORD=123456789'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=users_db'

  postgres_library_db:
    image: 'postgres:latest'
    ports:
      - 5431:5432
    environment:
      - 'POSTGRES_USER=aleshkey'
      - 'POSTGRES_PASSWORD=123456789'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=library_db'

  postgres_books_db:
    image: 'postgres:latest'
    ports:
      - 5430:5432
    environment:
      - 'POSTGRES_USER=aleshkey'
      - 'POSTGRES_PASSWORD=123456789'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=books_db'