spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: books-service
          uri:  http://localhost:8081
          predicates:
            - Path=/books/**
          filters:
            - AuthenticationFilter

        - id: library-service
          uri:  http://localhost:8082
          predicates:
            - Path=/library/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri:  http://localhost:9000
          predicates:
            - Path=/auth/**

  application:
    name: LIBRARY-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: http://localhost:8081/v3/api-docs
        name: Book Service
      - url: http://localhost:8082/v3/api-docs
        name: Library Service
      - url: http://localhost:9000/v3/api-docs
        name: Auth Service